# Generated by Django 3.2.4 on 2021-07-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210629_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='rut_servicio',
            new_name='id_servicio',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='razon_servicio',
            new_name='nombre_servicio',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='descripcion_servicio',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='servicio_servicio',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
