# Generated by Django 3.2.4 on 2021-07-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210630_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='id_servicio',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre_servicio',
            field=models.CharField(max_length=50, verbose_name=' NOMBRE_SERVICIO'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='rut_proveedor')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='nombre_o_razon')),
                ('descripcion', models.CharField(default='', max_length=100, verbose_name='descripcion')),
                ('email', models.CharField(default='', max_length=50, verbose_name='email')),
                ('telefono', models.CharField(default='', max_length=20, verbose_name='telefono')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicios')),
            ],
        ),
    ]
